CREATE TABLE IF NOT EXISTS frames (
    id SERIAL PRIMARY KEY,
    video_id INTEGER NOT NULL,
    link TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (video_id) REFERENCES videos(id) ON DELETE CASCADE
);
