// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package initialize

import (
	"database/sql"
	"mlvt/internal/handler/rest/v1/admin_handler"
	"mlvt/internal/handler/rest/v1/media_handler"
	"mlvt/internal/handler/rest/v1/mlvt_handler"
	"mlvt/internal/handler/rest/v1/ping_handler"
	"mlvt/internal/handler/rest/v1/progress_handler"
	"mlvt/internal/handler/rest/v1/user_handler"
	"mlvt/internal/handler/rest/v1/voucher_handler"
	"mlvt/internal/handler/rest/v1/wallet_handler"
	"mlvt/internal/infra/aws"
	"mlvt/internal/infra/db/mongodb"
	"mlvt/internal/pkg/middleware"
	"mlvt/internal/repo/admin_repo"
	"mlvt/internal/repo/media_repo"
	"mlvt/internal/repo/ping_repo"
	"mlvt/internal/repo/progress_repo"
	"mlvt/internal/repo/traffic_repo"
	"mlvt/internal/repo/user_repo"
	"mlvt/internal/repo/voucher_repo"
	"mlvt/internal/repo/wallet_repo"
	"mlvt/internal/router"
	"mlvt/internal/service"
	"mlvt/internal/service/admin_service"
	"mlvt/internal/service/auth_service"
	"mlvt/internal/service/media_service"
	"mlvt/internal/service/ping_service"
	"mlvt/internal/service/progress_service"
	"mlvt/internal/service/traffic_service"
	"mlvt/internal/service/user_service"
	"mlvt/internal/service/voucher_service"
	"mlvt/internal/service/wallet_service"
)

// Injectors from wire.go:

func InitializeApp(db *sql.DB, mongoConn *mongodb.MongoDBClient) (*router.AppRouter, error) {
	userRepository := user_repo.NewUserRepo(db)
	s3ClientInterface, err := aws.NewS3Client()
	if err != nil {
		return nil, err
	}
	string2 := _wireStringValue
	authServiceInterface := auth_service.NewAuthService(userRepository, string2)
	trafficRepository := traffic_repo.NewTrafficRepo(mongoConn)
	trafficService := traffic_service.NewTrafficService(trafficRepository, s3ClientInterface)
	userService := user_service.NewUserService(userRepository, s3ClientInterface, authServiceInterface, trafficService)
	userController := user_handler.NewUserController(userService)
	mediaRepository := media_repo.NewMediaRepo(db)
	mediaService := media_service.NewMediaService(mediaRepository, s3ClientInterface)
	mediaController := media_handler.NewMediaController(mediaService)
	progressRepository := progress_repo.NewProgressRepo(mongoConn)
	progressService := progress_service.NewProgressService(progressRepository, mediaRepository, s3ClientInterface)
	mlvtController := mlvt_handler.NewMlvtController(mediaService, progressService, trafficService)
	progressController := progress_handler.NewProgressService(progressService)
	pingRepository := ping_repo.NewPingRepo(db)
	pingService := ping_service.NewPingService(pingRepository)
	pingController := ping_handler.NewPingController(pingService)
	authUserMiddleware := middleware.NewAuthUserMiddleware(authServiceInterface)
	adminRepository := admin_repo.NewAminRepo(mongoConn, db)
	adminService := admin_service.NewAminService(userRepository, adminRepository, trafficService)
	adminController := admin_handler.NewAdminController(adminService)
	walletRepository := wallet_repo.NewWalletRepo(db)
	walletService := wallet_service.NewWalletService(walletRepository, trafficService)
	walletController := wallet_handler.NewWalletController(walletService)
	voucherRepository := voucher_repo.NewVoucherRepo(mongoConn)
	voucherService := voucher_service.NewVoucherService(voucherRepository, trafficService, walletService)
	voucherController := voucher_handler.NewVoucherController(voucherService)
	swaggerRouter := router.NewSwaggerRouter()
	appRouter := router.NewAppRouter(userController, mediaController, mlvtController, progressController, pingController, authUserMiddleware, adminController, walletController, voucherController, swaggerRouter)
	return appRouter, nil
}

var (
	_wireStringValue = service.SecretKey
)
