// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package initialize

import (
	"mlvt/internal/handler/rest/v1/admin_handler"
	"mlvt/internal/handler/rest/v1/media_handler"
	"mlvt/internal/handler/rest/v1/mlvt_handler"
	"mlvt/internal/handler/rest/v1/payment_handler"
	"mlvt/internal/handler/rest/v1/ping_handler"
	"mlvt/internal/handler/rest/v1/process_handler"
	"mlvt/internal/handler/rest/v1/progress_handler"
	"mlvt/internal/handler/rest/v1/token_claim_handler"
	"mlvt/internal/handler/rest/v1/user_handler"
	"mlvt/internal/handler/rest/v1/voucher_handler"
	"mlvt/internal/handler/rest/v1/wallet_handler"
	"mlvt/internal/infra/aws"
	"mlvt/internal/infra/db/mongodb"
	"mlvt/internal/pkg/middleware"
	"mlvt/internal/repo/admin_repo"
	"mlvt/internal/repo/media_repo"
	"mlvt/internal/repo/payment_repo"
	"mlvt/internal/repo/ping_repo"
	"mlvt/internal/repo/progress_repo"
	"mlvt/internal/repo/token_claim_repo"
	"mlvt/internal/repo/traffic_repo"
	"mlvt/internal/repo/user_repo"
	"mlvt/internal/repo/voucher_repo"
	"mlvt/internal/repo/wallet_repo"
	"mlvt/internal/router"
	"mlvt/internal/service"
	"mlvt/internal/service/admin_service"
	"mlvt/internal/service/auth_service"
	"mlvt/internal/service/email_service"
	"mlvt/internal/service/media_service"
	"mlvt/internal/service/notify_service"
	"mlvt/internal/service/payment_service"
	"mlvt/internal/service/ping_service"
	"mlvt/internal/service/progress_service"
	"mlvt/internal/service/token_claim_service"
	"mlvt/internal/service/traffic_service"
	"mlvt/internal/service/user_service"
	"mlvt/internal/service/voucher_service"
	"mlvt/internal/service/wallet_service"

	"github.com/jmoiron/sqlx"
)

// Injectors from wire.go:

func InitializeApp(db *sqlx.DB, mongoConn *mongodb.MongoDBClient) (*router.AppRouter, error) {
	// base repository / service
	userRepository := user_repo.NewUserRepo(db)
	emailService := email_service.NewEmailService()

	s3ClientInterface, err := aws.NewS3Client()
	if err != nil {
		return nil, err
	}
	string2 := _wireStringValue
	authServiceInterface := auth_service.NewAuthService(userRepository, string2)

	// Traffic
	trafficRepository := traffic_repo.NewTrafficRepo(mongoConn)
	trafficService := traffic_service.NewTrafficService(trafficRepository, s3ClientInterface)

	// User
	userService := user_service.NewUserService(userRepository, s3ClientInterface, authServiceInterface, trafficService, emailService)
	userController := user_handler.NewUserController(userService)

	// Media
	mediaRepository := media_repo.NewMediaRepo(db)
	mediaService := media_service.NewMediaService(mediaRepository, s3ClientInterface)
	mediaController := media_handler.NewMediaController(mediaService)

	// Progress
	progressRepository := progress_repo.NewProgressRepo(mongoConn)
	progressService := progress_service.NewProgressService(progressRepository, mediaRepository, s3ClientInterface)
	progressController := progress_handler.NewProgressService(progressService, mediaService)

	// Process (media + progress)
	processController := process_handler.NewProcessService(progressService, mediaService)

	// MLVT + Nofiy
	notifyService := notify_service.NewNotifyService()
	mlvtController := mlvt_handler.NewMlvtController(mediaService, progressService, trafficService, notifyService)

	// Ping 
	pingRepository := ping_repo.NewPingRepo(db)
	pingService := ping_service.NewPingService(pingRepository)
	pingController := ping_handler.NewPingController(pingService)

	// Admin
	adminRepository := admin_repo.NewAminRepo(mongoConn, db)
	adminService := admin_service.NewAminService(userRepository, adminRepository, trafficService)
	adminController := admin_handler.NewAdminController(adminService)

	// Wallet
	walletRepository := wallet_repo.NewWalletRepo(db)
	walletService := wallet_service.NewWalletService(walletRepository, trafficService)
	walletController := wallet_handler.NewWalletController(walletService)

	// Voucher 
	voucherRepository := voucher_repo.NewVoucherRepo(mongoConn)
	voucherService := voucher_service.NewVoucherService(voucherRepository, trafficService, walletService)
	voucherController := voucher_handler.NewVoucherController(voucherService)

	// Token
	tokenRepository := token_claim_repo.New(db)
	tokenService := token_claim_service.New(tokenRepository)
	tokenController := token_claim_handler.New(tokenService)

	// Middleware
	authUserMiddleware := middleware.NewAuthUserMiddleware(authServiceInterface)

	paymentRepository := payment_repo.NewPaymentRepo(mongoConn)
	paymentService := payment_service.NewPaymentService(paymentRepository, walletService, trafficService)
	paymentController := payment_handler.NewPaymentController(paymentService)
	swaggerRouter := router.NewSwaggerRouter()
	appRouter := router.NewAppRouter(userController, mediaController, mlvtController, progressController, processController, pingController, authUserMiddleware, adminController, walletController, voucherController, tokenController, paymentController, swaggerRouter)
	return appRouter, nil
}

var (
	_wireStringValue = service.SecretKey
)
