// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package initialize

import (
	"database/sql"
	"mlvt/internal/handler/rest/v1/admin_handler"
	"mlvt/internal/handler/rest/v1/audio_handler"
	"mlvt/internal/handler/rest/v1/mlvt_handler"
	"mlvt/internal/handler/rest/v1/payment_handler/momo_handler"
	"mlvt/internal/handler/rest/v1/ping_handler"
	"mlvt/internal/handler/rest/v1/progress_handler"
	"mlvt/internal/handler/rest/v1/transcription_handler"
	"mlvt/internal/handler/rest/v1/user_handler"
	"mlvt/internal/handler/rest/v1/video_handler"
	"mlvt/internal/handler/rest/v1/voucher_handler"
	"mlvt/internal/handler/rest/v1/wallet_handler"
	"mlvt/internal/infra/aws"
	"mlvt/internal/infra/db/mongodb"
	"mlvt/internal/pkg/middleware"
	"mlvt/internal/repo/admin_repo"
	"mlvt/internal/repo/audio_repo"
	"mlvt/internal/repo/payment_repo/momo_repo"
	"mlvt/internal/repo/ping_repo"
	"mlvt/internal/repo/progress_repo"
	"mlvt/internal/repo/traffic_repo"
	"mlvt/internal/repo/transcription_repo"
	"mlvt/internal/repo/user_repo"
	"mlvt/internal/repo/video_repo"
	"mlvt/internal/repo/voucher_repo"
	"mlvt/internal/repo/wallet_repo"
	"mlvt/internal/router"
	"mlvt/internal/service"
	"mlvt/internal/service/admin_service"
	"mlvt/internal/service/audio_service"
	"mlvt/internal/service/auth_service"
	"mlvt/internal/service/payment_service/momo_service"
	"mlvt/internal/service/ping_service"
	"mlvt/internal/service/progress_service"
	"mlvt/internal/service/traffic_service"
	"mlvt/internal/service/transcription_service"
	"mlvt/internal/service/user_service"
	"mlvt/internal/service/video_service"
	"mlvt/internal/service/voucher_service"
	"mlvt/internal/service/wallet_service"
)

// Injectors from wire.go:

func InitializeApp(db *sql.DB, mongoConn *mongodb.MongoDBClient) (*router.AppRouter, error) {
	userRepository := user_repo.NewUserRepo(db)
	s3ClientInterface, err := aws.NewS3Client()
	if err != nil {
		return nil, err
	}
	string2 := _wireStringValue
	authServiceInterface := auth_service.NewAuthService(userRepository, string2)
	trafficRepository := traffic_repo.NewTrafficRepo(mongoConn)
	trafficService := traffic_service.NewTrafficService(trafficRepository, s3ClientInterface)
	userService := user_service.NewUserService(userRepository, s3ClientInterface, authServiceInterface, trafficService)
	userController := user_handler.NewUserController(userService)
	videoRepository := video_repo.NewVideoRepo(db)
	videoService := video_service.NewVideoService(videoRepository, s3ClientInterface)
	videoController := video_handler.NewVideoController(videoService)
	audioRepository := audio_repo.NewAudioRepository(db)
	audioService := audio_service.NewAudioService(audioRepository, s3ClientInterface)
	transcriptionRepository := transcription_repo.NewTranscriptionRepository(db)
	transcriptionService := transcription_service.NewTranscriptionService(transcriptionRepository, s3ClientInterface)
	audioController := audio_handler.NewAudioController(audioService, transcriptionService)
	transcriptionController := transcription_handler.NewTranscriptionController(transcriptionService, videoService)
	progressRepository := progress_repo.NewProgressRepo(mongoConn)
	progressService := progress_service.NewProgressService(progressRepository, videoRepository, s3ClientInterface)
	mlvtController := mlvt_handler.NewMlvtController(audioService, transcriptionService, videoService, progressService, trafficService)
	progressController := progress_handler.NewProgressService(progressService)
	pingRepository := ping_repo.NewPingRepo(db)
	pingService := ping_service.NewPingService(pingRepository)
	pingController := ping_handler.NewPingController(pingService)
	authUserMiddleware := middleware.NewAuthUserMiddleware(authServiceInterface)
	adminRepository := admin_repo.NewAminRepo(mongoConn)
	adminService := admin_service.NewAminService(userRepository, adminRepository, trafficService)
	adminController := admin_handler.NewAdminController(adminService)
	walletRepository := wallet_repo.NewWalletRepo(db)
	walletService := wallet_service.NewWalletService(walletRepository, trafficService)
	walletController := wallet_handler.NewWalletController(walletService)
	voucherRepository := voucher_repo.NewVoucherRepo(mongoConn)
	voucherService := voucher_service.NewVoucherService(voucherRepository)
	voucherController := voucher_handler.NewVoucherController(voucherService)
	moMoRepo := momo_repo.NewMoMoRepo()
	moMoPaymentService := momo_service.NewMoMoPaymentService(moMoRepo)
	moMoPaymentController := momo_handler.NewMoMoPaymentHandler(moMoPaymentService)
	swaggerRouter := router.NewSwaggerRouter()
	appRouter := router.NewAppRouter(userController, videoController, audioController, transcriptionController, mlvtController, progressController, pingController, authUserMiddleware, adminController, walletController, voucherController, moMoPaymentController, swaggerRouter)
	return appRouter, nil
}

var (
	_wireStringValue = service.SecretKey
)
