// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"mlvt/internal/handler/rest/v1"
	"mlvt/internal/infra/aws"
	"mlvt/internal/pkg/middleware"
	"mlvt/internal/repo"
	"mlvt/internal/router"
	"mlvt/internal/service"
)

// Injectors from wire.go:

func InitializeApp(db *sql.DB, s3Client *aws.S3Client) (*router.AppRouter, error) {
	userRepository := repo.NewUserRepo(db)
	string2 := _wireStringValue
	authService := service.NewAuthService(userRepository, string2)
	userService := service.NewUserService(userRepository, s3Client, authService)
	userController := handler.NewUserController(userService)
	videoRepository := repo.NewVideoRepo(db)
	videoService := service.NewVideoService(videoRepository, s3Client)
	videoController := handler.NewVideoController(videoService)
	audioRepository := repo.NewAudioRepository(db)
	audioService := service.NewAudioService(audioRepository, s3Client)
	audioController := handler.NewAudioController(audioService)
	transcriptionRepository := repo.NewTranscriptionRepository(db)
	transcriptionService := service.NewTranscriptionService(transcriptionRepository, s3Client)
	transcriptionController := handler.NewTranscriptionController(transcriptionService)
	authUserMiddleware := middleware.NewAuthUserMiddleware(authService)
	swaggerRouter := router.NewSwaggerRouter()
	appRouter := router.NewAppRouter(userController, videoController, audioController, transcriptionController, authUserMiddleware, swaggerRouter)
	return appRouter, nil
}

var (
	_wireStringValue = service.SecretKey
)
